version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_SERVER_URL=http://localhost:3000
    depends_on:
      - server
    networks:
      - imposter-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://imposter:imposter123@postgres:5432/imposter
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - imposter-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=imposter
      - POSTGRES_USER=imposter
      - POSTGRES_PASSWORD=imposter123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - imposter-network
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    networks:
      - imposter-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  imposter-network:
    driver: bridge
